# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ma_messages.proto',
  package='',
  serialized_pb='\n\x11ma_messages.proto\"i\n\rMA_SimInitMsg\x12\x13\n\x0btotal_users\x18\x01 \x02(\x05\x12\x14\n\x0c\x61\x63tion_space\x18\x02 \x02(\x05\x12\x13\n\x0bstate_space\x18\x03 \x02(\x05\x12\x18\n\x10state_space_type\x18\x04 \x02(\x05\"1\n\rMA_SimInitAck\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\x12\n\nstopSimReq\x18\x02 \x01(\x08\"B\n\x14MA_SchedulingRequest\x12\x0f\n\x07user_id\x18\x01 \x02(\x05\x12\r\n\x05state\x18\x02 \x03(\x05\x12\n\n\x02SN\x18\x03 \x02(\x05\"U\n\x17MA_SchedulingRequestSyn\x12\x0f\n\x07user_id\x18\x01 \x02(\x05\x12\r\n\x05state\x18\x02 \x03(\x05\x12\n\n\x02SN\x18\x03 \x02(\x05\x12\x0e\n\x06reward\x18\x04 \x02(\x02\"[\n\x15MA_NeighborTableEntry\x12\r\n\x05pos_x\x18\x01 \x02(\x02\x12\r\n\x05pos_y\x18\x02 \x02(\x02\x12\x0f\n\x07seq_num\x18\x03 \x02(\x05\x12\x13\n\x0blast_update\x18\x04 \x02(\x05\"B\n\x10MA_NeighborTable\x12.\n\x0eneighbor_table\x18\x01 \x03(\x0b\x32\x16.MA_NeighborTableEntry\"t\n\x1bMA_SchedulingRequestSynDist\x12\x0f\n\x07user_id\x18\x01 \x02(\x05\x12(\n\x08neighbor\x18\x02 \x03(\x0b\x32\x16.MA_NeighborTableEntry\x12\n\n\x02SN\x18\x03 \x02(\x05\x12\x0e\n\x06reward\x18\x04 \x02(\x02\"V\n\x18SPS_SchedulingRequestSyn\x12\x0f\n\x07user_id\x18\x01 \x02(\x05\x12\r\n\x05state\x18\x02 \x03(\x01\x12\n\n\x02SN\x18\x03 \x02(\x05\x12\x0e\n\x06reward\x18\x04 \x02(\x02\"A\n\x12MA_SchedulingGrant\x12\x12\n\ntime_stamp\x18\x01 \x02(\x05\x12\x17\n\x0fstop_simulation\x18\x02 \x01(\x08\"<\n\rMA_RewardSent\x12\x0f\n\x07user_id\x18\x01 \x02(\x05\x12\n\n\x02SN\x18\x02 \x02(\x05\x12\x0e\n\x06reward\x18\x03 \x02(\x02\"7\n\x10MA_RewardSentAll\x12#\n\x0b\x61ll_rewards\x18\x01 \x03(\x0b\x32\x0e.MA_RewardSent')




_MA_SIMINITMSG = descriptor.Descriptor(
  name='MA_SimInitMsg',
  full_name='MA_SimInitMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='total_users', full_name='MA_SimInitMsg.total_users', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action_space', full_name='MA_SimInitMsg.action_space', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state_space', full_name='MA_SimInitMsg.state_space', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state_space_type', full_name='MA_SimInitMsg.state_space_type', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=126,
)


_MA_SIMINITACK = descriptor.Descriptor(
  name='MA_SimInitAck',
  full_name='MA_SimInitAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='done', full_name='MA_SimInitAck.done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stopSimReq', full_name='MA_SimInitAck.stopSimReq', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=128,
  serialized_end=177,
)


_MA_SCHEDULINGREQUEST = descriptor.Descriptor(
  name='MA_SchedulingRequest',
  full_name='MA_SchedulingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='MA_SchedulingRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='MA_SchedulingRequest.state', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SN', full_name='MA_SchedulingRequest.SN', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=179,
  serialized_end=245,
)


_MA_SCHEDULINGREQUESTSYN = descriptor.Descriptor(
  name='MA_SchedulingRequestSyn',
  full_name='MA_SchedulingRequestSyn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='MA_SchedulingRequestSyn.user_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='MA_SchedulingRequestSyn.state', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SN', full_name='MA_SchedulingRequestSyn.SN', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reward', full_name='MA_SchedulingRequestSyn.reward', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=247,
  serialized_end=332,
)


_MA_NEIGHBORTABLEENTRY = descriptor.Descriptor(
  name='MA_NeighborTableEntry',
  full_name='MA_NeighborTableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pos_x', full_name='MA_NeighborTableEntry.pos_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pos_y', full_name='MA_NeighborTableEntry.pos_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seq_num', full_name='MA_NeighborTableEntry.seq_num', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_update', full_name='MA_NeighborTableEntry.last_update', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=334,
  serialized_end=425,
)


_MA_NEIGHBORTABLE = descriptor.Descriptor(
  name='MA_NeighborTable',
  full_name='MA_NeighborTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='neighbor_table', full_name='MA_NeighborTable.neighbor_table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=427,
  serialized_end=493,
)


_MA_SCHEDULINGREQUESTSYNDIST = descriptor.Descriptor(
  name='MA_SchedulingRequestSynDist',
  full_name='MA_SchedulingRequestSynDist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='MA_SchedulingRequestSynDist.user_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='neighbor', full_name='MA_SchedulingRequestSynDist.neighbor', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SN', full_name='MA_SchedulingRequestSynDist.SN', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reward', full_name='MA_SchedulingRequestSynDist.reward', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=495,
  serialized_end=611,
)


_SPS_SCHEDULINGREQUESTSYN = descriptor.Descriptor(
  name='SPS_SchedulingRequestSyn',
  full_name='SPS_SchedulingRequestSyn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='SPS_SchedulingRequestSyn.user_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='SPS_SchedulingRequestSyn.state', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SN', full_name='SPS_SchedulingRequestSyn.SN', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reward', full_name='SPS_SchedulingRequestSyn.reward', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=613,
  serialized_end=699,
)


_MA_SCHEDULINGGRANT = descriptor.Descriptor(
  name='MA_SchedulingGrant',
  full_name='MA_SchedulingGrant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time_stamp', full_name='MA_SchedulingGrant.time_stamp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stop_simulation', full_name='MA_SchedulingGrant.stop_simulation', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=701,
  serialized_end=766,
)


_MA_REWARDSENT = descriptor.Descriptor(
  name='MA_RewardSent',
  full_name='MA_RewardSent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='MA_RewardSent.user_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SN', full_name='MA_RewardSent.SN', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reward', full_name='MA_RewardSent.reward', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=768,
  serialized_end=828,
)


_MA_REWARDSENTALL = descriptor.Descriptor(
  name='MA_RewardSentAll',
  full_name='MA_RewardSentAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='all_rewards', full_name='MA_RewardSentAll.all_rewards', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=830,
  serialized_end=885,
)

_MA_NEIGHBORTABLE.fields_by_name['neighbor_table'].message_type = _MA_NEIGHBORTABLEENTRY
_MA_SCHEDULINGREQUESTSYNDIST.fields_by_name['neighbor'].message_type = _MA_NEIGHBORTABLEENTRY
_MA_REWARDSENTALL.fields_by_name['all_rewards'].message_type = _MA_REWARDSENT
DESCRIPTOR.message_types_by_name['MA_SimInitMsg'] = _MA_SIMINITMSG
DESCRIPTOR.message_types_by_name['MA_SimInitAck'] = _MA_SIMINITACK
DESCRIPTOR.message_types_by_name['MA_SchedulingRequest'] = _MA_SCHEDULINGREQUEST
DESCRIPTOR.message_types_by_name['MA_SchedulingRequestSyn'] = _MA_SCHEDULINGREQUESTSYN
DESCRIPTOR.message_types_by_name['MA_NeighborTableEntry'] = _MA_NEIGHBORTABLEENTRY
DESCRIPTOR.message_types_by_name['MA_NeighborTable'] = _MA_NEIGHBORTABLE
DESCRIPTOR.message_types_by_name['MA_SchedulingRequestSynDist'] = _MA_SCHEDULINGREQUESTSYNDIST
DESCRIPTOR.message_types_by_name['SPS_SchedulingRequestSyn'] = _SPS_SCHEDULINGREQUESTSYN
DESCRIPTOR.message_types_by_name['MA_SchedulingGrant'] = _MA_SCHEDULINGGRANT
DESCRIPTOR.message_types_by_name['MA_RewardSent'] = _MA_REWARDSENT
DESCRIPTOR.message_types_by_name['MA_RewardSentAll'] = _MA_REWARDSENTALL

class MA_SimInitMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_SIMINITMSG
  
  # @@protoc_insertion_point(class_scope:MA_SimInitMsg)

class MA_SimInitAck(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_SIMINITACK
  
  # @@protoc_insertion_point(class_scope:MA_SimInitAck)

class MA_SchedulingRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_SCHEDULINGREQUEST
  
  # @@protoc_insertion_point(class_scope:MA_SchedulingRequest)

class MA_SchedulingRequestSyn(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_SCHEDULINGREQUESTSYN
  
  # @@protoc_insertion_point(class_scope:MA_SchedulingRequestSyn)

class MA_NeighborTableEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_NEIGHBORTABLEENTRY
  
  # @@protoc_insertion_point(class_scope:MA_NeighborTableEntry)

class MA_NeighborTable(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_NEIGHBORTABLE
  
  # @@protoc_insertion_point(class_scope:MA_NeighborTable)

class MA_SchedulingRequestSynDist(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_SCHEDULINGREQUESTSYNDIST
  
  # @@protoc_insertion_point(class_scope:MA_SchedulingRequestSynDist)

class SPS_SchedulingRequestSyn(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPS_SCHEDULINGREQUESTSYN
  
  # @@protoc_insertion_point(class_scope:SPS_SchedulingRequestSyn)

class MA_SchedulingGrant(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_SCHEDULINGGRANT
  
  # @@protoc_insertion_point(class_scope:MA_SchedulingGrant)

class MA_RewardSent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_REWARDSENT
  
  # @@protoc_insertion_point(class_scope:MA_RewardSent)

class MA_RewardSentAll(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MA_REWARDSENTALL
  
  # @@protoc_insertion_point(class_scope:MA_RewardSentAll)

# @@protoc_insertion_point(module_scope)
